from . import account_move
from . import analytic_line
from . import bonus
from . import product_product
from . import product_template
from . import project_task
from . import res_company
from . import res_config_settings
from . import sale_order
from . import sale_order_line
from . import stock_picking
